# Generated by Django 5.2.12 on 2026-03-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Miembro del grupo',
                'verbose_name_plural': 'Miembros del grupo',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='TherapistPatientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('paused', 'Pausado'), ('ended', 'Finalizado')], default='pending', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('chat_enabled', models.BooleanField(default=False, help_text='Feature flag global del chat con IA')),
                ('session_frequency_days', models.IntegerField(default=14)),
            ],
            options={
                'verbose_name': 'Vínculo terapeuta–paciente',
                'verbose_name_plural': 'Vínculos terapeuta–paciente',
                'ordering': ['-invited_at'],
            },
        ),
    ]
