# Generated by Django 5.2.12 on 2026-03-15 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.therapistprofile'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='links.group'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='therapistpatientlink',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='links.group'),
        ),
        migrations.AddField(
            model_name='therapistpatientlink',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_links', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='therapistpatientlink',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='users.therapistprofile'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'patient'), name='links_groupmembership_unique_group_patient'),
        ),
        migrations.AddConstraint(
            model_name='therapistpatientlink',
            constraint=models.UniqueConstraint(fields=('therapist', 'patient'), name='links_therapistpatientlink_unique_therapist_patient'),
        ),
    ]
