# Generated by Django 5.2.12 on 2026-03-16 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0003_journalentry_group'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('is_system', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_feelings', to='users.therapistprofile')),
            ],
            options={
                'verbose_name': 'sentimiento',
                'verbose_name_plural': 'sentimientos',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryFeeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry_feelings', to='feelings.feeling')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry_feelings', to='journal.journalentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='feeling',
            constraint=models.UniqueConstraint(fields=('title', 'therapist'), name='feelings_unique_feeling_per_therapist'),
        ),
        migrations.AddConstraint(
            model_name='journalentryfeeling',
            constraint=models.UniqueConstraint(fields=('journal_entry', 'feeling'), name='feelings_unique_journalentry_feeling'),
        ),
    ]
