.PHONY: run migrate shell test createsuperuser

run:
	python manage.py runserver

migrate:
	python manage.py makemigrations
	python manage.py migrate

shell:
	python manage.py shell

test:
	python manage.py test

createsuperuser:
	python manage.py createsuperuser
