# Generated by Django 5.2.12 on 2026-03-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('reminder_frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('never', 'Nunca')], default='daily', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Preferencia de notificación',
                'verbose_name_plural': 'Preferencias de notificación',
                'ordering': ['patient'],
            },
        ),
        migrations.CreateModel(
            name='SessionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('notify_before_days', models.PositiveIntegerField(default=1, help_text='Días antes de la sesión para notificar')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Alerta de sesión',
                'verbose_name_plural': 'Alertas de sesión',
                'ordering': ['-session_date'],
            },
        ),
    ]
