# Generated by Django 5.2.12 on 2026-03-15 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0002_initial'),
        ('notifications', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='sessionalert',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_alerts', to='links.therapistpatientlink'),
        ),
    ]
