# Generated by Django 5.2.12 on 2026-03-15 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_ai', models.TextField(help_text='Texto generado por Claude')),
                ('body_edited', models.TextField(blank=True, help_text='Texto editado por el paciente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('undo_deadline', models.DateTimeField(blank=True, help_text='sent_at + 15 segundos', null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='links.therapistpatientlink')),
            ],
            options={
                'verbose_name': 'Resumen',
                'verbose_name_plural': 'Resúmenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SummaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_entries', to='journal.journalentry')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_entries', to='summaries.summary')),
            ],
            options={
                'verbose_name': 'Entrada en resumen',
                'verbose_name_plural': 'Entradas en resumen',
                'ordering': ['-included_at'],
                'constraints': [models.UniqueConstraint(fields=('summary', 'journal_entry'), name='summaries_summaryentry_unique_summary_journal')],
            },
        ),
    ]
