# Generated by Django 5.2.12 on 2026-03-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='research_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='research_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
